# Applications
cask "1password"
cask "1password-cli"
cask "visual-studio-code"
cask "raycast"
cask "spotify"
cask "cmux"
cask "aspire"
cask "font-jetbrains-mono-nerd-font"
cask "logi-options+"

# CLI tools
brew "fnm"
brew "starship"
brew "gh"
brew "pnpm"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "jq"
brew "lazygit"
brew "sqlcmd"

brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
